site_name: Micormake documentation
site_url: https://micromake.github.io
site_description: >-
  Micromake documentation.

repo_name: micromake.github.io
repo_url: https://github.com/micromake/micromake.github.io

extra:
  alternate:
    - name: English
      link: "javascript:translateTo('english');"
      lang: en
    - name: Français
      link: "javascript:translateTo('french');"
      lang: fr
    - name: 한국어
      link: "javascript:translateTo('korean');"
      lang: kr
    - name: 日本語
      link: "javascript:translateTo('japanese');"
      lang: ja
    - name: 中文
      link: "javascript:translateTo('chinese_simplified');"
      lang: zh
      
plugins:
  - search:
      separator: '[\s\u200b\-]'

# ------------------- 导航配置 -------------------
nav:
  - 导览: index.md
  - DIY套件:
    - 简介: 2.md
    - 组装指南: 2.md
  - 升级套件:
    - 1.md
  - 机械部件:
    - 1.md
  - 控制屏:
    - 1.md
  - 控制板:
    - 1.md
  - 驱动板:
    - 1.md
  - 传感器:
    - 1.md
  - 教程:
    - 1.md

theme:
  icon: 
    # logo: material/github
    repo: fontawesome/brands/github
    alternate: material/web

  name: material
  language: zh

  features:
    - content.code.copy
    - content.code.annotate
    - content.tooltips
    # - navigation.expand #导航展开
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - instant
    # - header.autohide
    # - navigation.path
    # - announce.dismiss
    # - content.action.edit #编辑页面
    # - content.action.view #查看源码

  palette:

    # Palette toggle for light mode
    - scheme: default
      primary: white
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details

extra_css:
  - css/extra.css
  - css/extra2.css
  - css/customize.css
  - css/ziti.css

extra_javascript:
  - js/glm-config.js
  - js/glm-translate.js
